export { default as IconArrowUpRightSquare } from "./IconArrowUpRightSquare.svelte"
export { default as IconDribbble } from "./IconDribbble.svelte"
export { default as IconEnvelope } from "./IconEnvelope.svelte"
export { default as IconGithub } from "./IconGithub.svelte"
export { default as IconTelegram } from "./IconTelegram.svelte"
